### ISSUE TITLE
causes infinite loops on voxel engine >= 0.6.0

### ISSUE THREAD

**Issue by max-mapper** [max-mapper/voxel-highlight#3] opened 2013-03-01 03:42 UTC
I think when the new voxel raycaster implementation was introduced (https://github.com/maxogden/voxel-engine/commit/0f7fbec09b5d0eb26574b5cd83d481960696fbbf) something happened that caused voxel-highlight to freeze the game and make infinite loops

![Screen Shot 2013-02-28 at 7 40 28 PM](https://f.cloud.github.com/assets/39759/208320/ce71b0f0-8221-11e2-864c-56e72afc498a.png)

this is taken after the game has frozen. note how the last X value is 0... also the highlights arent showing up

I will fix this when I get some time, for now I'm trying to get the hello-world back to a stable state

cc @theoxylo

**Comment by theoxylo** [comment] 2013-03-01 16:39
I have been experiencing this and looking into the cause. I plan to spend some time on it today.

I think it may be related to handling negative coordinates in Chunker getBlock, but I am not sure.

**Comment by theoxylo** [comment] 2013-03-01 17:37
The problem appears to be in voxel-raycast/raycast.js traceRay when step becomes 0 for very small values of ox, oy, or oz. See the log statement I added below:

```
function traceRay(voxels, origin, direction, max_d, hit_pos, hit_norm) {
  var ox = origin[0]
    , oy = origin[1]
    , oz = origin[2]
    , dx = direction[0]
    , dy = direction[1]
    , dz = direction[2]
    , ds = Math.sqrt(dx*dx + dy*dy + dz*dz)
    , norm_axis = 0;
  dx /= ds;
  dy /= ds;
  dz /= ds;

  if(!max_d) {
    max_d = 64.0;
  }

  //Step block-by-block along ray
  var t = 0.0;
  while(t <= max_d) {
    var ix = Math.floor(ox)
      , iy = Math.floor(oy)
      , iz = Math.floor(oz);

    var b = voxels.getBlock(ix, iy, iz);
    if(b != 0) {
      if(hit_pos) {
        hit_pos[0] = ox;
        hit_pos[1] = oy;
        hit_pos[2] = oz;
      }
      if(hit_norm) {
        hit_norm[0] = hit_norm[1] = hit_norm[2] = 0;
        if(norm_axis > 0) {
          hit_norm[norm_axis-1] = 1;
        } else if(norm_axis < 0) {
          hit_norm[-1-norm_axis] = -1;
        }
      }
      return b;
    }

    var step = 0.5;

    var fx = ox - ix;
    var fy = oy - iy;
    var fz = oz - iz;

    if(dx < -0.0001) {
      if(fx < 0.0001)
        fx = 1.0;
      var s = -fx/dx;
      if(s < step) {
        norm_axis = 1;
        step = s;
      }
    }
    if(dx > 0.0001) {
      var s = (1.0-fx)/dx;
      if(s < step) {
        norm_axis = -1;
        step = s;
      }
    }

    if(dy < -0.0001) {
      if(fy < 0.0001)
        fy = 1.0;
      var s = -fy/dy;
      if(s < step) {
        norm_axis = 2;
        step = s;
      }
    }
    if(dy > 0.0001) {
      var s = (1.0-fy)/dy;
      if(s < step) {
        norm_axis = -2;
        step = s;
      }
    }

    if(dz < -0.0001) {
      if(fz < 0.0001)
        fz = 1.0;
      var s = -fz/dz;
      if(s < step) {
        norm_axis = 3;
        step = s;
      }
    }
    if(dz > 0.0001) {
      var s = (1.0-fz)/dz;
      if(s < step) {
        norm_axis = -3;
        step = s;
      }
    }
    if (step === 0)
    {
      console.log("step is 0! fx: " + fx + ", fy: " + fy + ", fz: " + fz);
      step = 0.1;
    }
    t += step;
    ox += dx * step;
    oy += dy * step;
    oz += dz * step;
  }
  return -1;
}
```

**Comment by max-mapper** [comment] 2013-03-01 21:02
cc @mikolalysenko

**Comment by mikolalysenko** [comment] 2013-03-01 21:46
Ok, I think what was going on was the code was inconsistently handling half-open intervals for the faces of the cubes.  The new version should fix this problem, and as a bonus it will also now properly handle intersections against open faces.  So if there is a voxel at [0,0,0] and you do:

raycast([-10, 0.5, 0.5], [1,0,0])

You will hit at position [0, 0.5, 0.5].  On the other hand if you do:

raycast([10, 0.5, 0.5], [-1,0,0])

You will hit at position [0.99999, 0.5, 0.5]

**Comment by theoxylo** [comment] 2013-03-01 22:27
fixed in pull request. I used a cheaper "lite" raycast impl that doesn't deal with normals or anything fancy

**Closed as completed** 2013-03-01 23:40 UTC
